# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Taskmem < Formula
  desc "Task-tracking CLI for LLM agents, backed by PostgreSQL"
  homepage "https://github.com/shajith-dev/taskmem"
  version "0.2.0"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/shajith-dev/taskmem/releases/download/v0.2.0/taskmem_0.2.0_darwin_amd64.tar.gz"
      sha256 "19938110592606b9299b7f1a848609ca6b6089979f9af552673567bfa42b33e4"

      define_method(:install) do
        bin.install "taskmem"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/shajith-dev/taskmem/releases/download/v0.2.0/taskmem_0.2.0_darwin_arm64.tar.gz"
      sha256 "99a8ea412ef4ff78bca90fe90a435863fa3b6005c2e0afd6711cf60635d9db7f"

      define_method(:install) do
        bin.install "taskmem"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/shajith-dev/taskmem/releases/download/v0.2.0/taskmem_0.2.0_linux_amd64.tar.gz"
      sha256 "3df466ab4a81073e7da3c554fc5707f34beee11ddf056e0559ed5ef28296ffd4"
      define_method(:install) do
        bin.install "taskmem"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/shajith-dev/taskmem/releases/download/v0.2.0/taskmem_0.2.0_linux_arm64.tar.gz"
      sha256 "129b22bafe72502b6a0c08f2767c8fdcd12904f3c2e92b9b824c4dac278824d7"
      define_method(:install) do
        bin.install "taskmem"
      end
    end
  end

  test do
    system "#{bin}/taskmem version"
  end
end
