# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Taskmem < Formula
  desc "Task-tracking CLI for LLM agents, backed by PostgreSQL"
  homepage "https://github.com/shajith-dev/taskmem"
  version "0.4.0"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/shajith-dev/taskmem/releases/download/v0.4.0/taskmem_0.4.0_darwin_amd64.tar.gz"
      sha256 "544cd03eba04ae1ec39d03498be3a8f8177038f22925bd72f783c95301c1f237"

      define_method(:install) do
        bin.install "taskmem"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/shajith-dev/taskmem/releases/download/v0.4.0/taskmem_0.4.0_darwin_arm64.tar.gz"
      sha256 "87ef6bbdf6b8e84bd8c23393d83021189c396e96d3ce661d102dc71c5d03ac06"

      define_method(:install) do
        bin.install "taskmem"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/shajith-dev/taskmem/releases/download/v0.4.0/taskmem_0.4.0_linux_amd64.tar.gz"
      sha256 "1a67121eda66a823d88a16a6ceeea5ec258352ff15e9f73b2ead2888380844d5"
      define_method(:install) do
        bin.install "taskmem"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/shajith-dev/taskmem/releases/download/v0.4.0/taskmem_0.4.0_linux_arm64.tar.gz"
      sha256 "ccf02b04610de6215b6dcd083f238da3b6ad1b1db75d5229ac06607a6086d87e"
      define_method(:install) do
        bin.install "taskmem"
      end
    end
  end

  test do
    system "#{bin}/taskmem version"
  end
end
