# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Taskmem < Formula
  desc "Task-tracking CLI for LLM agents, backed by PostgreSQL"
  homepage "https://github.com/shajith-dev/taskmem"
  version "0.4.1"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/shajith-dev/taskmem/releases/download/v0.4.1/taskmem_0.4.1_darwin_amd64.tar.gz"
      sha256 "6fdbe10db7ca8c496a1ee670611faf27edceea695de1110fbac2ac3948536e7e"

      define_method(:install) do
        bin.install "taskmem"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/shajith-dev/taskmem/releases/download/v0.4.1/taskmem_0.4.1_darwin_arm64.tar.gz"
      sha256 "794c5f4775c12d338256ff3726f2444eea11e6eb902c9b575e68d447cafe06ce"

      define_method(:install) do
        bin.install "taskmem"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/shajith-dev/taskmem/releases/download/v0.4.1/taskmem_0.4.1_linux_amd64.tar.gz"
      sha256 "a10b4e77e10e5052db55aa8bdb0900a41450265306437961590f72ced3d1c296"
      define_method(:install) do
        bin.install "taskmem"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/shajith-dev/taskmem/releases/download/v0.4.1/taskmem_0.4.1_linux_arm64.tar.gz"
      sha256 "e6470fdb43e871eea81957a43cfd1bbe2be6fbc4166a676f06e82b3948fb4a7f"
      define_method(:install) do
        bin.install "taskmem"
      end
    end
  end

  test do
    system "#{bin}/taskmem version"
  end
end
